### ISSUE TITLE
Error Installing Sample Data and Magento

### ISSUE THREAD

**Issue by brandontamm** [alexcheng1982/docker-magento#1]
How would I mount to the magento data files so I can edit the files?

How do you do this - it doesn't seem like there is a way to do this via your setup?

**Comment by tabr0201** [comment]
Newbie Issue...lol...problem resolved

**Comment by alexcheng1982** [comment]
The installation script has been renamed to install-sampledata.

**Comment by alexcheng1982** [comment]
The purpose of this docker image is to quickly create an environment for development and testing, so I included the sample data files in the image itself.

You can either ssh to the running container and edit them directly, or create your own docker compose file with [volumes](https://docs.docker.com/compose/yml/#volumes), e.g.

``` yml
volumes:
 - /your/local/:/var/www/htdocs/var/media
```
