### ISSUE TITLE
Forbidden if I use: docker-compose-dev.yml

### ISSUE THREAD

**Issue by jujes** [alexcheng1982/docker-magento#11]
![screen shot 2016-07-23 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/2881017/17077949/ca4b6bde-50e4-11e6-9b92-cc39a538280d.png)

**Comment by sivajik34** [comment]
I faced same issue only.@jujes issue resolved?

**Comment by nhammond101** [comment]
i have the same issue, changing the dockerfile to install magento and sample data into _/var/www/html_ instead of _/var/www/htdocs_ seems to work
Nb. you'll also need to change the install-sampledata and install-magento scripts with the new path if required.

**Comment by alexcheng1982** [comment]
Does this 403 error happen before of after installation? Cannot reproduce locally.

**Comment by alexcheng1982** [comment]
See #14. Fixed in latest Docker Hub build.
