### ISSUE TITLE
How to use this repo for windows 10?

### ISSUE THREAD

**Issue by sivajik34** [alexcheng1982/docker-magento#13]
when i ran following commands i'm getting following issues.
$ docker-compose up -d
Pulling mysql (mysql:5.6.23)...
5.6.23: Pulling from library/mysql

[0B95caeb02: Pulling fs layer
[0Bbfd4d273: Pulling fs layer
[0B4764414d: Pulling fs layer
[0B44cb6556: Pulling fs layer
[0Bd6fa1e8b: Pulling fs layer
[0Bc70d8b44: Pulling fs layer
[0Bab2827b0: Pulling fs layer
[0B986d5d45: Pulling fs layer
Digest: sha256:6e1cbc80b84c5b9925793c5b341ade007f9203d1d097e3a952003b93f0a09ecd   888 B/888 BkBBB
Status: Downloaded newer image for mysql:5.6.23
Creating admin_mysql_1
Creating admin_web_1

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint admin_web_1 (53d1ea46d846742e651cfafbb89a81c047b00fcd69c3432f794550f3e67ba224): Bind for 0.0.0.0:80 failed: port is already allocated
[31mERROR[0m: Encountered errors while bringing up the project.

$ docker exec -it 666674054a8d install-sampledata
rpc error: code = 2 desc = oci runtime error: exec failed: exec: "install-sampledata": executable file not found in $PATH

**Comment by alexcheng1982** [comment]
This means the port `80` on your machine is already taken by some other application, possibly IIS. You should modify the `docker-compose.yml` file to choose a different port, e.g. change to port `8080` as below.

```
  ports:
    - "8080:80"
```
