### ISSUE TITLE
Installing 1.9.2.4 error permission accessing

### ISSUE THREAD

**Issue by ysilvela** [alexcheng1982/docker-magento#14]
After install I obtains this error when I invoke the web:

You don't have permission to access / on this server.

**Comment by alexcheng1982** [comment]
This is the same issue as #11.

The reason is the default site of Apache 2 was enabled, but the default site used `/var/www/html` as the document root, which is different from the `/var/www/htdocs`. I modified the Apache 2 config to use `/var/www/htdocs` as the document root.

**Comment by alexcheng1982** [comment]
The latest build in Docker Hub has fixed this issue.
