### ISSUE TITLE
Database credentials on first install

### ISSUE THREAD

**Issue by zeljkoprsa** [alexcheng1982/docker-magento#2]
Tried the credentials from the github readme and still couldn't pass this step. What am i doing wrong? Screenshot: https://www.dropbox.com/s/d9nnkfv9qj73qlz/Screenshot%202015-06-03%2017.15.38.png?dl=0

**Comment by alexcheng1982** [comment]
This docker image is designed to work with an existing mysql database. You need to have an existing mysql server before starting the Magento docker images. 

If you use [Docker compose](https://docs.docker.com/compose/) to run this image, then you can use the `install-magento` script to install Magento. In this case, a mysql server will be started automatically.

If you run this images as a standalone container, you need to input the correct mysql server information in the Magento installation UI.
