### ISSUE TITLE
Unable to install magento 1.6.2

### ISSUE THREAD

**Issue by shahdewang** [alexcheng1982/docker-magento#9]
I updated the docker-compose.yml to use **alexcheng/magento:1.6.2.0** as the image. Ran **docker-compose up -d** and the containers did come up. However, on running **install-magento** (after installing sample data) I am getting following error -

> FAILED
> ERROR: Database server does not support the InnoDB storage engine.

**Comment by shahdewang** [comment]
I solved it with help from this post - http://stackoverflow.com/questions/15443448/magento-install-complains-about-missing-innodb-when-it-is-available. However, accessing http://local.magento/ works fine but http://local.magento/admin return 404.

**Comment by shahdewang** [comment]
http://local.magento/index.php/admin works!

**Comment by alexcheng1982** [comment]
Thank you for the report. I realised that the 1.6.2.0 branch was broken. So I updated the branch with a couple of fixes:
- Install Magento PHP 5.4 patch
- For the InnoDB storage engine issue, I added a new script `enable-mysql-5.6-support` to apply the core fix to Magento. You can use the new script to fix the InnoDB storage engine issue.
- Upgrade to use Docker Compose v2 format
